add_library(viz2d)
target_sources(viz2d
    PRIVATE
        viz2d.cpp
        viz2d.hpp
)
target_link_libraries(viz2d
    PUBLIC
        nbody
        raylib
)

add_library(viz3d)
target_sources(viz3d
    PRIVATE 
        viz3d.cpp 
        viz3d.hpp 
)
target_link_libraries(viz3d
    PUBLIC 
        nbody 
        raylib
)

add_executable(visualizer)
target_sources(visualizer
    PRIVATE
        main.cpp
)
target_link_libraries(visualizer
    PRIVATE
        viz2d
        viz3d
)
